project:
  type: udea-thesis

lang: es

book:
  title: "Título del trabajo de grado"
  subtitle: "Subtítutlo del trabajo de grado"
  author: 
    - name: "Autor Trabajo-Grado"
      affiliations:
        - name: "Universidad de Antioquia"
          department: "Instituto de Biología"
  chapters: 
    - index.qmd
    - capitulo_01/index.qmd
    - capitulo_02/index.qmd
    - capitulo_03/index.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

date: today
date-format: "YYYY"

format:
  udea-thesis-pdf: default
  udea-thesis-html: default