project:
  type: udea-thesis

date: today
date-format: iso

lang: es

bibliography: references.bib
csl: apa.csl

format:
  udea-thesis-pdf: default
  udea-thesis-html: default

book:
  chapters: 
    - index.qmd
    - capitulo_00/index.qmd
    - capitulo_01/index.qmd
    - capitulo_02/index.qmd
    - capitulo_03/index.qmd
    - capitulo_04/index.qmd
    - capitulo_05/index.qmd
    - capitulo_06/index.qmd
    - capitulo_07/index.qmd
    - capitulo_08/index.qmd
    - capitulo_09/index.qmd
    - capitulo_10/index.qmd
    - capitulo_11/index.qmd
    - capitulo_12/index.qmd
    # - references.qmd
  appendices: 
    - anexos/anexo_00.qmd
    - anexos/anexo_01.qmd
    - anexos/anexo_02.qmd
    - anexos/anexo_03.qmd
    - anexos/anexo_04.qmd
    
title: "Título del trabajo de grado"
author: 
  - name: "Nombre Primer Autor"
  - name: "Nombre Segundo Autor"
tipo-documento: "Tipo de trabajo"
titulo-otorgado: "Nombre del título"
tipo-orientador: "Tipo de orientador"
nombre-orientador: "Nombre del orientador"
titulo_orientador: "Título académico mas alto"
unidad-academica: "Facultad, escuela, instituto o corporación"
programa: "Pregrado o posgrado"
ciudad: "Ciudad"
ano-grado: "año de grado"

citacion: "Primer Autor & Segundo Autor" # No incluir el año
referencia: "Primer Autor, N. & Segundo Autor, N." # Sólo incluir los nombres
modalidad-grado: "Modalidad de grado"

licencia-tipo: assets/license/by-nc-sa.png

cohorte-posgrado: "posgrado en numero romano"
grupo-investigacion: "Nombre grupo de investigación"
centro_investigacion: "Nombre centro de investigación"

biblioteca: "Nombre biblioteca, CRAI o centro de documentación"

rector: "Nombres y Apellidos del rector"
decano-director: "Nombres y Apellidos del decano o director"
jefe-departamento: "Nombres y Apellidos del jefe de departamento"

# cita:
#   texto: "Texto de la cita"
#   autor: "Autor de la cita"

dedicatoria: |
  Texto de dedicatoria
agradecimientos: |
  Texto de agradecimientos

abreviaturas: "abreviaturas.tex"