# Citas y referencias de material legal (leyes, decretos, sentencias, etc.

Uno de los aspectos que más puede causar confusión en Normas APA es lo referente a la citación de material legal y jurídico; de hecho, la misma American Psychological Association refiere al uso del manual internacional "Bluebook: A Uniform System of Citation" (este estilo está incluido en Mendeley y otros gestores bibliográficos), pues estos dos estilos difieren en su formato de cita y referencia, pues las publicaciones legales citan las referencias al pie de página, en tanto que en el estilo APA se ubican todas las fuentes bibliográficas, incluyendo aquellas de materiales legales, en la lista de referencias. Si deseas conocer y adaptar los lineamientos del Bluebook, puedes consultarlos en <https://www.legalbluebook.com/>; asimismo, algunos ejemplos del manual de la APA están basados en el sistema jurídico estadounidense, lo que sin duda podría causar cierto conflicto con el entorno legal colombiano; ambos serán aceptados en los trabajos de grado y tesis de la Universidad de Antioquia. Sin embargo, para facilitar y adaptar las citas y referencias al sistema legal y jurídico colombiano, recomendamos los siguientes lineamientos basados en Normas APA como primera alternativa de citación y referenciación de los materiales más comunes en Colombia, a saber, leyes, decretos, sentencias, resoluciones, códigos, constitución política, entre otros. La primera recomendación está basada en el prefijo Colombia. como autor corporativo estatal, luego la subentidad y el año. Ejemplos de citas y referencias (se incluye un ejemplo internacional de España).

En el listado de referencias legales se ilustras algunos ejemplos de como adaptar las referencias tipo *\@book* al formato APA para referencias legales colombianas (observe el uso de $"\{\}"$ dobles en el Autor)
